class ArtisanServices {
  static const List<String> services = [
    'AC Technician',
    'Accountant',
    'App Developer',
    'Appliance Repairer',
    'Baker',
    'Barber',
    'Beautician',
    'Bookkeeper',
    'Bouncer',
    'Bricklayer',
    'Business Coach',
    'Carpenter',
    'Upholsterer',
    'Caterer',
    'Chef',
    'Content Writer',
    'Courier',
    'Customer Service Representative',
    'Data Analyst',
    'Delivery Driver',
    'Dispatch Rider',
    'Dog Walker',
    'Driver',
    'Dry Cleaner',
    'Electrician',
    'Event Planner',
    'Financial Advisor',
    'Gardener',
    'Generator Repairer',
    'Graphic Designer',
    'Hairdresser',
    'House Cleaner',
    'HR Consultant',
    'Insurance Agent',
    'Interior Designer',
    'Interpreter',
    'IT Support',
    'Landscaper',
    'Legal Consultant',
    'Locksmith',
    'Makeup Artist',
    'Marketing Consultant',
    'Masseuse',
    'Mobile Phone Technician',
    'Mechanic',
    'Nanny',
    'Painter',
    'Personal Assistant',
    'Personal Trainer',
    'Pest Control',
    'Photographer',
    'Plumber',
    'Pool Cleaner',
    'Project Manager',
    'Public Relations Specialist',
    'Real Estate Agent',
    'Roofer',
    'Security Guard',
    'SEO Specialist',
    'Shoe Maker',
    'Social Media Manager',
    'Software Engineer',
    'Software Tester',
    'Solar Installer',
    'Tailor',
    'Taxi Driver',
    'Tiler',
    'Travel Agent',
    'Usher',
    'Video Editor',
    'Videographer',
    'Virtual Assistant',
    'Voice Over Artist',
    'Vulcanizer',
    'Watch Repairer',
    'Web Developer',
    'Welder',
    'Other',
  ];
}
